# -*- mode: ruby -*-
# vi: set ft=ruby :


# $update_script=<<SCRIPT
# apt-get update
# apt-get upgrade
# apt-get install nginx tmux git python3 python3-pip -y
# pip3 install numpy
# SCRIPT

Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu2204"

  config.vm.define :master do |master|
    config.vm.provider "virtualbox" do |vb|
      vb.cpus = '2'
      vb.memory = "4096"
    end
    master.vm.network :private_network, ip: "192.168.56.11"
    master.vm.hostname = "tpos-master"
  
    # master.vm.provision "shell", :inline => $update_script
  end

  config.vm.provision "shell", path: "provision_basic.sh"
  config.vm.synced_folder "./shared", "/home/vagrant/shared",
    owner: "www-data", group: "www-data"
  config.vm.network "forwarded_port", guest: 80, host: 8000

end
